"use client";

/**
 * useJsSvg — runs a model-generated JavaScript `blouseSvg(state) -> string`
 * function in the browser to render the blouse as SVG.
 *
 * The function is generated by the backend (POST /myod/js-code) but executed
 * ONLY in the browser (sandboxed by default — no access to server tokens, the
 * DB, or the backend). The model code never runs on the server.
 *
 * Runs natively via `new Function` — no Pyodide, no WASM download. Renders are
 * microseconds. A timeout guard prevents a bad function from freezing the UI.
 *
 * NOTE on safety: this uses `new Function`/`eval` on model output, which is a
 * code-execution risk. The browser sandbox limits the blast radius (no server
 * secrets), but model-generated code could still touch the DOM or loop. For
 * full isolation, run it in a Web Worker instead. This simpler version is
 * opt-in (Vector-fn mode).
 */

import { useCallback, useRef, useState } from "react";

export interface JsSvgApi {
  /** Whether a function is currently being compiled. */
  loading: boolean;
  /** Error from the last compile/run, if any. */
  error: string | null;
  /** Compile the model-generated code into a callable fn. */
  defineFn: (code: string) => Promise<void>;
  /** Run `blouseSvg(state)` and return the SVG string (microseconds). */
  renderSvg: (state: Record<string, string>) => Promise<string>;
}

const RENDER_TIMEOUT_MS = 500;

export function useJsSvg(): JsSvgApi {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fnRef = useRef<((state: Record<string, string>) => unknown) | null>(null);

  const defineFn = useCallback(async (code: string) => {
    setLoading(true);
    setError(null);
    try {
      // The model emits e.g. `const blouseSvg = (state) => {...}` or
      // `function blouseSvg(state) {...}`. Normalize to a bare function
      // EXPRESSION and eval it directly (wrapped in parens) — this avoids
      // scoping quirks where a top-level `const` inside `new Function` isn't
      // reachable from a return statement in strict browsers.
      let expr = code.trim();
      expr = expr.replace(/^const\s+blouseSvg\s*=\s*/, "");
      expr = expr.replace(/^let\s+blouseSvg\s*=\s*/, "");
      expr = expr.replace(/^var\s+blouseSvg\s*=\s*/, "");
      expr = expr.replace(/;+\s*$/, "");
      // eslint-disable-next-line no-new-func
      const fn = new Function(`return (${expr});`)() as
        | ((state: Record<string, string>) => unknown)
        | undefined;
      if (typeof fn !== "function") {
        throw new Error("Renderer did not define a blouseSvg function.");
      }
      // Smoke-test with empty + a populated state.
      const probeEmpty = fn({});
      const probeFull = fn({ blouse_cut: "Simple cut", front_neck: "Round" });
      for (const [label, val] of [["{}", probeEmpty], ["sample", probeFull]]) {
        if (typeof val !== "string" || !val.trim().startsWith("<svg")) {
          throw new Error(`Renderer returned invalid SVG for ${label} state.`);
        }
      }
      fnRef.current = fn;
    } catch (e) {
      fnRef.current = null;
      setError(e instanceof Error ? e.message : "Invalid renderer code.");
      throw e;
    } finally {
      setLoading(false);
    }
  }, []);

  const renderSvg = useCallback(
    async (state: Record<string, string>): Promise<string> => {
      const fn = fnRef.current;
      if (!fn) throw new Error("Renderer not ready.");
      // Run with a timeout guard so a bad function can't freeze the UI long.
      return new Promise<string>((resolve, reject) => {
        const timer = setTimeout(() => {
          reject(new Error("Renderer timed out."));
        }, RENDER_TIMEOUT_MS);
        try {
          const out = fn(state);
          clearTimeout(timer);
          if (typeof out !== "string" || !out.trim().startsWith("<svg")) {
            reject(new Error("Renderer produced invalid SVG."));
            return;
          }
          resolve(out);
        } catch (e) {
          clearTimeout(timer);
          reject(e instanceof Error ? e : new Error("Renderer failed."));
        }
      });
    },
    [],
  );

  return { loading, error, defineFn, renderSvg };
}
